### ISSUE TITLE
changes to local database access

### ISSUE THREAD

**Issue by williamgunn** [equihuam/BliblioSqlite#1]
Hey @equihuam , there are some changes to the local database in the latest version of Mendeley which may break your script. We're currently collecting use cases to officially support local database access so we don't break things in the future, so if you'd like to give the Mendeley developers some feedback on what data you need to access so we can make sure to support your use case, please get in touch via email.

**Comment by equihuam** [comment]
Thank you for reaching out. Indeed stop working!!!.  This little tool is just used to do some housekeeping. It would be nice to have those tasks available inside the Mendeley desktop!!!! 
Basically, it does a counting of reference collections under different conditions (groups, downloaded files, missing files and so on). I found some cases where the directory where the references were located was inconsistent, so I added an option to check on that and means to regain consistency.  I also found that there could be some inconsistencies on how the title of documents is written (upper, lower, title, and so on), so I added an option to have it the same way in all my collection.
